language: ruby
rvm:
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - RAILS_ENV=test rake db:schema:load
  - bundle exec m
  - echo $?

notifications:
  email: false

# use new travis infrastructure
sudo: false

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
